apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: manga-service
  name: manga-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manga-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: manga-service
    spec:
      containers:
        - env:
            - name: RABBITMQ_EXCHANGE_NAME
              value: exchange
            - name: RABBITMQ_QUEUE_NAME
              value: manga-news
            - name: RABBITMQ_ROUTING_KEY
              value: manga_routing_key
            - name: SPRING_DATA_MONGODB_DATABASE
              value: Content-database
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://admin:admin@cluster0.59c6b49.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
          image: mymanga-manga:latest
          name: manga
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
