apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.12-management-alpine
          name: rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5552
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          volumeMounts:
            - mountPath: ./RabbitMQ:/etc/rabbitmq
              name: rabbitmq-cm0
          imagePullPolicy: Never
      restartPolicy: Always
      volumes:
        - configMap:
            name: rabbitmq-cm0
          name: rabbitmq-cm0
