apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: RABBITMQ_EXCHANGE_NAME
              value: exchange
            - name: RABBITMQ_QUEUE_NAME
              value: manga-news
            - name: RABBITMQ_ROUTING_KEY
              value: manga_routing_key
            - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
              value: "0"
            - name: SPRING_DATASOURCE_PASSWORD
              value: YourStrongPassword1!
            - name: SPRING_DATASOURCE_URL
              value: jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true;
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
          image: mymanga-user:latest
          name: user
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
