name: Spring boot CD flow

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build User-Backend with Maven
      run: mvn clean install --file User/pom.xml

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jgeven/mymanga-user
        tags: latest
        registry: docker.io
        dockerfile: MyManga-UserSystem/Dockerfile
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
